coverage:
  status:
    project:
      default:
        # basic
        target: 5%
        threshold: 1%
        if_ci_failed: error #success, failure, error, ignore
        informational: false
        only_pulls: false
    patch:
      default:
        target: 5%
        threshold: 1%
